name: build-windows-installer
on: 
    push:
        branches: [ latest ]
jobs:
    build:
        runs-on: ubuntu-latest
        
        steps: 
        - uses: actions/checkout@v2
        - name: PyInstaller Windows
          uses: JackMcKew/pyinstaller-action-windows@main
          with:
            path: src
        - uses: actions/upload-artifact@v2
          with:
            name: lepg
            path: src/dist/windows